on:
  push:
    branches: main
  pull_request:
    branches: main
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render and deploy

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        # uncomment and fill to pin a version
        # with:
        #   version: 0.9.105

      # - name: Setup R
      #   uses: r-lib/actions/setup-r@v2
      #   # with:
      #   #   r-version: '3.5.3' # The R version to download (if necessary) and use.
      # - name: Install R packages
      #   run: Rscript -e 'install.packages(c("rmarkdown", "numbers"))

      - name: Render to all format
        # Add any command line argument needed
        run: |
          quarto render --to html

      - name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        # Beware of the action permission as stated here:
        # https://github.com/JamesIves/github-pages-deploy-action#permission-settings-%EF%B8%8F
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: gh-pages
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: _site
